### ISSUE TITLE
run.sh not working; application not compiling

### ISSUE THREAD

**Issue by alxb421** [TristanWellman/TermBot#1]
When running the `run.sh`:
```sh
./run.sh: line 3: cd: Desktop/Cbot/src/com/company: No such file or directory
gcc: error: bot.c: No such file or directory
./run.sh: line 7: ./bot: No such file or directory
```

When executing `gcc bot.c -o bot -pthread -ldiscord -lcurl -lcrypto -lm`:

```
bot.c:7:10: fatal error: orca/discord.h: No such file or directory
    7 | #include <orca/discord.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by TristanWellman** [comment]
You probably need to install orca.
```https://github.com/cee-studio/orca```

This version on github doesn't include the cloud storage system either so I wouldn't be reliant on that if that is something you want to use.
